@startuml
start
:вы входите в продуктовый
магазин;
if(вы собираетесь купить
много ?) then (да)
:возьмите тележку;
else (нет)
:возьмите корзину;
endif
:выдвигайтесь за
покупками;
repeat
:проверьте список покупок ;
:берите продукты по списку;
repeat while (ести ли продукты которые вы не взяли?) is (да) not (нет)
:идите на кассу;
if(оплата картой?) then(да)
:достаньте банковскую карту;
else (нет)
:достаньте кошелек с наличными;
endif
:оплатите;
:соберите покупки в пакет(-ы);
:вы выходите из магазина;
end
@enduml